import express,{type Request,type Response,type NextFunction} from 'express';
import helmet from 'helmet';
import rateLimit from 'express-rate-limit';
import cookieParser from 'cookie-parser';
import {z} from 'zod';
import {randomUUID} from 'node:crypto';
import {join,resolve} from 'node:path';
import {mkdirSync,readFileSync,writeFileSync,statfsSync} from 'node:fs';
import {openDatabase,transaction,type DB} from './db';
import {box,digest,equal,fail,hashPassword,html,HttpError,now,safePath,token,uuid,verifyPassword} from './security';
import type {FileRecord,Site} from '../shared/types';

type Actor={userId:string;csrf?:string;deviceVault?:string;deviceId?:string};
declare global {namespace Express{interface Request{actor?:Actor}}}
export interface Config {dataDir:string;origin:string;bootstrapCode:string;production?:boolean;staticDir?:string;quotaBytes?:number;disableRateLimit?:boolean}
export function createApp(config:Config) {
 const app=express(), db=openDatabase(config.dataDir); const quota=config.quotaBytes??10*1024**3;
 mkdirSync(join(config.dataDir,'chunks'),{recursive:true,mode:0o700});
 app.disable('x-powered-by');app.set('trust proxy','loopback');
 app.use(helmet({contentSecurityPolicy:config.production?{directives:{defaultSrc:["'self'"],scriptSrc:["'self'"],styleSrc:["'self'","'unsafe-inline'"],imgSrc:["'self'",'data:','blob:','https:'],connectSrc:["'self'"],fontSrc:["'self'",'data:'],workerSrc:["'self'",'blob:'],objectSrc:["'none'"],frameAncestors:["'none'"],upgradeInsecureRequests:[]}}:false}));
 app.use(cookieParser());
 app.use('/api',(req,res,next)=>{res.set('Cache-Control','no-store');next();});
 const rate=(limit:number,windowMs=60_000)=>config.disableRateLimit?((_req:Request,_res:Response,next:NextFunction)=>next()):rateLimit({limit,windowMs,standardHeaders:'draft-8',legacyHeaders:false});
 app.use('/api',rate(900));
 // Raw binary chunks must be parsed before JSON. JSON routes have explicit limits.
 app.use('/api',express.raw({type:'application/octet-stream',limit:'2mb'}));
 app.use('/api',express.json({limit:'32mb'}));
 app.use('/api',(req,res,next)=>{try{
  const auth=req.get('authorization');
  if(auth){const t=/^Bearer ([A-Za-z0-9_-]{43})$/.exec(auth)?.[1];if(!t)fail(401,'Invalid device credential.');const d=db.prepare('SELECT * FROM devices WHERE hash=?').get(digest(t)) as any;if(!d)fail(401,'Device access was revoked.');req.actor={userId:d.user_id,deviceVault:d.vault_id,deviceId:d.id};db.prepare('UPDATE devices SET last_used_at=? WHERE id=?').run(now(),d.id);}
  else if(req.cookies.flint_session){const s=db.prepare('SELECT * FROM sessions WHERE hash=? AND expires>?').get(digest(req.cookies.flint_session),Date.now()) as any;if(s)req.actor={userId:s.user_id,csrf:s.csrf};}
  if(!['GET','HEAD','OPTIONS'].includes(req.method)){
   const origin=req.get('origin');
   if(origin&&origin!==config.origin)fail(403,'This origin is not allowed.');
   if(req.get('sec-fetch-site')==='cross-site')fail(403,'Cross-site writes are not allowed.');
   const publicWrite=/^\/api\/(auth\/(login|register)|published\/[^/]+\/unlock)\/?$/.test(req.originalUrl.split('?')[0]);
   if(!publicWrite&&!req.actor)fail(401,'Please sign in.');
   if(!publicWrite&&req.actor?.csrf&&!equal(req.get('x-csrf-token')||'',req.actor.csrf))fail(403,'Refresh the page before saving.','CSRF');
  }
  next();
 }catch(e){next(e);}});
 function actor(req:Request){if(!req.actor)fail(401,'Please sign in.');return req.actor;}
 function browser(req:Request){const a=actor(req);if(a.deviceId)fail(403,'Use the signed-in web application for this action.');return a;}
 function access(req:Request,id:string,write=false,owner=false){uuid.parse(id);const a=actor(req);if(a.deviceVault&&a.deviceVault!==id)fail(403,'Device belongs to another vault.');const m=db.prepare('SELECT role FROM members WHERE vault_id=? AND user_id=?').get(id,a.userId) as any;if(!m)fail(403,'You do not have access to this vault.');if(write&&m.role==='viewer')fail(403,'This vault is read only.');if(owner&&(m.role!=='owner'||a.deviceId))fail(403,'Only the vault owner can do this.');return m.role as string;}
 function vault(req:Request,id:string){const role=access(req,id);const v=db.prepare('SELECT * FROM vaults WHERE id=?').get(id) as any;return{id:v.id,name:v.name,salt:v.salt,keyBox:JSON.parse(v.key_box),epoch:v.epoch,role,createdAt:v.created_at};}
 function log(a:string,action:string,target:string){db.prepare('INSERT INTO audit(actor_id,action,target_id,created_at) VALUES(?,?,?,?)').run(a,action,target,now());}
 function prune(id:string){const v=db.prepare('SELECT retention_days FROM vaults WHERE id=?').get(id) as any;if(!v)return;db.prepare('DELETE FROM revisions WHERE vault_id=? AND updated_at<? AND revision < (SELECT revision FROM files WHERE files.vault_id=revisions.vault_id AND files.id=revisions.file_id)').run(id,new Date(Date.now()-v.retention_days*86400_000).toISOString());db.prepare('DELETE FROM mutations WHERE vault_id=? AND created_at<?').run(id,new Date(Date.now()-30*86400_000).toISOString());}
 function maintenance(){transaction(db,()=>{for(const v of db.prepare('SELECT id FROM vaults').all() as any[])prune(v.id);db.prepare('DELETE FROM sessions WHERE expires<?').run(Date.now());db.prepare('DELETE FROM public_sessions WHERE expires<?').run(Date.now());db.prepare('DELETE FROM invites WHERE expires<?').run(Date.now());});}
 function publicationSize(siteId:string){const n=db.prepare('SELECT coalesce(sum(length(CAST(content AS BLOB))),0) n FROM published_notes WHERE site_id=?').get(siteId) as any,a=db.prepare('SELECT coalesce(sum(length(data)),0) n FROM published_assets WHERE site_id=?').get(siteId) as any;return Number(n.n)+Number(a.n);}
 function usage(id:string){const a=db.prepare('SELECT coalesce(sum(length(box)),0) n FROM revisions WHERE vault_id=?').get(id) as any,b=db.prepare('SELECT coalesce(sum(bytes),0) n FROM chunks WHERE vault_id=?').get(id) as any,c=db.prepare('SELECT coalesce(sum(length(response)),0) n FROM mutations WHERE vault_id=?').get(id) as any,d=db.prepare('SELECT coalesce(sum(length(box)+coalesce(length(manifest_box),0)),0) n FROM files WHERE vault_id=?').get(id) as any;return Number(a.n)+Number(b.n)+Number(c.n)+Number(d.n)+(db.prepare('SELECT id FROM sites WHERE vault_id=?').all(id) as any[]).reduce((n,s)=>n+publicationSize(s.id),0);}
 function capacity(bytes:number){const s=statfsSync(config.dataDir);if(s.bavail*s.bsize<bytes+1024**3)fail(507,'Server storage is nearly full. Your local changes remain queued.');}
 function setSession(res:Response,userId:string){const secret=token(),csrf=token();db.prepare('INSERT INTO sessions(hash,user_id,csrf,expires) VALUES(?,?,?,?)').run(digest(secret),userId,csrf,Date.now()+30*86400_000);res.cookie('flint_session',secret,{httpOnly:true,secure:!!config.production,sameSite:'strict',maxAge:30*86400_000,path:'/'});return{user:db.prepare('SELECT id,email,name FROM users WHERE id=?').get(userId),csrf};}
 const loginInput=z.object({email:z.email().max(254).transform(v=>v.toLowerCase()),password:z.string().min(12).max(256)});
 app.get('/api/health',(_req,res)=>res.json({ok:true,version:'0.1.0'}));
 app.post('/api/auth/register',rate(10,15*60_000),async(req,res)=>{
  const x=loginInput.extend({name:z.string().trim().min(1).max(100),code:z.string().optional(),invite:z.string().optional()}).parse(req.body);
  const invitation=x.invite?db.prepare('SELECT * FROM invites WHERE hash=? AND expires>? AND used_by IS NULL').get(digest(x.invite),Date.now()) as any:null;
  if(!invitation&&(!config.bootstrapCode||!equal(x.code||'',config.bootstrapCode)))fail(403,'An invitation or registration code is required.');
  if(db.prepare('SELECT id FROM users WHERE email=?').get(x.email))fail(409,'This email already has an account.');
  const passwordHash=await hashPassword(x.password),id=randomUUID();
  transaction(db,()=>{db.prepare('INSERT INTO users(id,email,name,password_hash,created_at) VALUES(?,?,?,?,?)').run(id,x.email,x.name,passwordHash,now());if(invitation){const n=db.prepare('UPDATE invites SET used_by=? WHERE hash=? AND used_by IS NULL AND expires>?').run(id,digest(x.invite!),Date.now());if(!n.changes)fail(409,'Invitation is no longer available.');db.prepare('INSERT INTO members(vault_id,user_id,role) VALUES(?,?,?)').run(invitation.vault_id,id,invitation.role);}log(id,'register',id);});
  res.status(201).json(setSession(res,id));
 });
 app.post('/api/auth/login',rate(15,15*60_000),async(req,res)=>{const x=loginInput.parse(req.body),u=db.prepare('SELECT * FROM users WHERE email=?').get(x.email) as any;if(!u||!await verifyPassword(x.password,u.password_hash))fail(401,'Email or password is incorrect.');const fresh=db.prepare('SELECT password_hash FROM users WHERE id=?').get(u.id) as any;if(fresh?.password_hash!==u.password_hash)fail(401,'Account credentials changed. Sign in again.');log(u.id,'login',u.id);res.json(setSession(res,u.id));});
 app.get('/api/auth/me',(req,res)=>{const a=browser(req);res.json({user:db.prepare('SELECT id,email,name FROM users WHERE id=?').get(a.userId),csrf:a.csrf});});
 app.post('/api/auth/logout',(req,res)=>{browser(req);if(req.cookies.flint_session)db.prepare('DELETE FROM sessions WHERE hash=?').run(digest(req.cookies.flint_session));res.clearCookie('flint_session',{path:'/'}).json({ok:true});});
 app.post('/api/auth/password',async(req,res)=>{const a=browser(req),x=z.object({password:z.string().max(256),newPassword:z.string().min(12).max(256)}).parse(req.body),u=db.prepare('SELECT * FROM users WHERE id=?').get(a.userId) as any;if(!await verifyPassword(x.password,u.password_hash))fail(403,'Current password is incorrect.');const h=await hashPassword(x.newPassword);transaction(db,()=>{const n=db.prepare('UPDATE users SET password_hash=? WHERE id=? AND password_hash=?').run(h,a.userId,u.password_hash);if(!n.changes)fail(409,'Account credentials changed. Sign in again.');db.prepare('DELETE FROM sessions WHERE user_id=?').run(a.userId);});res.json(setSession(res,a.userId));});
 app.get('/api/vaults',(req,res)=>{const a=actor(req);let rows=db.prepare('SELECT vault_id FROM members WHERE user_id=? ORDER BY rowid').all(a.userId) as any[];if(a.deviceVault)rows=rows.filter(r=>r.vault_id===a.deviceVault);res.json({vaults:rows.map(r=>vault(req,r.vault_id))});});
 app.post('/api/vaults',(req,res)=>{const a=browser(req),x=z.object({id:uuid,name:z.string().trim().min(1).max(100),salt:z.string().min(20).max(100),keyBox:box}).parse(req.body);if((db.prepare('SELECT count(*) n FROM members WHERE user_id=? AND role=\'owner\'').get(a.userId) as any).n>=50)fail(400,'Vault limit reached.');transaction(db,()=>{db.prepare('INSERT INTO vaults(id,name,salt,key_box,created_at) VALUES(?,?,?,?,?)').run(x.id,x.name,x.salt,JSON.stringify(x.keyBox),now());db.prepare('INSERT INTO members(vault_id,user_id,role) VALUES(?,?,?)').run(x.id,a.userId,'owner');log(a.userId,'vault.create',x.id);});res.status(201).json({vault:vault(req,x.id)});});
 app.get('/api/vaults/:id',(req,res)=>res.json({vault:vault(req,String(req.params.id))}));
 app.get('/api/vaults/:id/files',(req,res)=>{const id=String(req.params.id);access(req,id);const after=z.coerce.number().int().min(0).default(0).parse(req.query.after),rows=db.prepare('SELECT * FROM files WHERE vault_id=? AND seq>? ORDER BY seq LIMIT 501').all(id,after) as any[],hasMore=rows.length>500,files=rows.slice(0,500).map(fileRecord);res.json({files,cursor:files.length?files[files.length-1].seq:after,hasMore});});
 app.get('/api/vaults/:id/manifests',(req,res)=>{const id=String(req.params.id);access(req,id);const after=z.coerce.number().int().min(0).default(0).parse(req.query.after),rows=db.prepare('SELECT vault_id,id,revision,epoch,manifest_box,deleted,updated_at,seq FROM files WHERE vault_id=? AND seq>? ORDER BY seq LIMIT 501').all(id,after) as any[],files=rows.slice(0,500).map(r=>({id:r.id,vaultId:r.vault_id,revision:r.revision,epoch:r.epoch,manifestBox:r.manifest_box?JSON.parse(r.manifest_box):undefined,deleted:!!r.deleted,updatedAt:r.updated_at,seq:r.seq}));res.json({files,cursor:files.length?files[files.length-1].seq:after,hasMore:rows.length>500});});
 app.get('/api/vaults/:id/files/:fileId',(req,res)=>{const id=String(req.params.id);access(req,id);const fid=uuid.parse(req.params.fileId),revision=z.coerce.number().int().positive().optional().parse(req.query.revision);const row=revision?db.prepare('SELECT *,file_id AS id FROM revisions WHERE vault_id=? AND file_id=? AND revision=?').get(id,fid,revision):db.prepare('SELECT * FROM files WHERE vault_id=? AND id=?').get(id,fid);if(!row)fail(404,'File revision not found.');res.json({file:fileRecord(row)});});
 app.get('/api/vaults/:id/files/:fileId/history',(req,res)=>{const id=String(req.params.id),fid=uuid.parse(req.params.fileId);access(req,id);const before=z.coerce.number().int().positive().default(Number.MAX_SAFE_INTEGER).parse(req.query.before);const rows=db.prepare('SELECT *,file_id AS id FROM revisions WHERE vault_id=? AND file_id=? AND revision<? ORDER BY revision DESC LIMIT 101').all(id,fid,before),files=rows.slice(0,100).map(fileRecord);res.json({files,hasMore:rows.length>100,nextBefore:files.length?files[files.length-1].revision:null});});
 const manifestBox=box.extend({data:box.shape.data.max(8192)});
 const writeInput=z.object({id:uuid,baseRevision:z.number().int().min(0),epoch:z.number().int().positive(),box,manifestBox:manifestBox.optional(),deleted:z.boolean(),mutationId:uuid}).strict();
 app.put('/api/vaults/:id/files/:fileId',(req,res)=>{const id=String(req.params.id),fid=uuid.parse(req.params.fileId);access(req,id,true);const x=writeInput.parse(req.body);if(x.id!==fid)fail(400,'File ID mismatch.');const rh=digest(JSON.stringify(x));const result=transaction(db,()=>{
  const v=db.prepare('SELECT * FROM vaults WHERE id=?').get(id) as any;
  const replay=db.prepare('SELECT * FROM mutations WHERE vault_id=? AND id=?').get(id,x.mutationId) as any;
  if(replay){if(replay.request_hash!==rh)fail(409,'Mutation ID was already used with different content.');return JSON.parse(replay.response);}
  if(x.epoch!==v.epoch)fail(412,'Vault encryption changed. Unlock again before syncing.','EPOCH_CHANGED');
  const old=db.prepare('SELECT * FROM files WHERE vault_id=? AND id=?').get(id,fid) as any;
  if((old?.revision??0)!==x.baseRevision)fail(409,'This file changed on another device.','REVISION_CONFLICT',old?{file:fileRecord(old)}:{});
  prune(id);const cipher=JSON.stringify(x.box),manifest=x.manifestBox?JSON.stringify(x.manifestBox):null;
  const seq=v.seq+1,revision=x.baseRevision+1,updated=now();
  const file:FileRecord={id:fid,vaultId:id,revision,epoch:x.epoch,box:x.box,...(x.manifestBox?{manifestBox:x.manifestBox}:{}),deleted:x.deleted,updatedAt:updated,seq};const response={file};
  const replayResponse=JSON.stringify(response),addedBytes=cipher.length*2+(manifest?.length??0)+replayResponse.length-(old?.box.length??0)-(old?.manifest_box?.length??0);
  capacity((cipher.length*2+(manifest?.length??0)+replayResponse.length)*2);if(usage(id)+addedBytes>quota)fail(413,'Vault storage limit reached.');
  db.prepare('UPDATE vaults SET seq=? WHERE id=?').run(seq,id);
  db.prepare('INSERT INTO files(vault_id,id,revision,epoch,box,manifest_box,deleted,updated_at,seq) VALUES(?,?,?,?,?,?,?,?,?) ON CONFLICT(vault_id,id) DO UPDATE SET revision=excluded.revision,epoch=excluded.epoch,box=excluded.box,manifest_box=excluded.manifest_box,deleted=excluded.deleted,updated_at=excluded.updated_at,seq=excluded.seq').run(id,fid,revision,x.epoch,cipher,manifest,+x.deleted,updated,seq);
  db.prepare('INSERT INTO revisions(vault_id,file_id,revision,epoch,box,deleted,updated_at,seq) VALUES(?,?,?,?,?,?,?,?)').run(id,fid,revision,x.epoch,cipher,+x.deleted,updated,seq);
  db.prepare('INSERT INTO mutations(vault_id,id,request_hash,response,created_at) VALUES(?,?,?,?,?)').run(id,x.mutationId,rh,replayResponse,updated);
  // Keep all tombstones and current heads; prune only history older than retention.
  db.prepare('DELETE FROM revisions WHERE vault_id=? AND updated_at<? AND revision < (SELECT revision FROM files WHERE files.vault_id=revisions.vault_id AND files.id=revisions.file_id)').run(id,new Date(Date.now()-v.retention_days*86400_000).toISOString());
  return response;
 });res.json(result);});
 app.put('/api/vaults/:id/chunks/:chunkId',(req,res)=>{const id=String(req.params.id),cid=uuid.parse(req.params.chunkId);access(req,id,true);if(!Buffer.isBuffer(req.body)||req.body.length<28)fail(400,'Encrypted binary chunk required.');const bytes=req.body as Buffer,h=digest(bytes),old=db.prepare('SELECT * FROM chunks WHERE vault_id=? AND id=?').get(id,cid) as any;if(old){if(old.hash!==h)fail(409,'Chunk IDs are immutable.');res.json({id:cid});return;}capacity(bytes.length*2);if(usage(id)+bytes.length>quota)fail(413,'Vault storage limit reached.');const folder=join(config.dataDir,'chunks',id);mkdirSync(folder,{recursive:true,mode:0o700});const p=join(folder,cid);try{writeFileSync(p,bytes,{mode:0o600,flag:'wx'});}catch(e:any){if(e.code!=='EEXIST'||digest(readFileSync(p))!==h)throw e;}db.prepare('INSERT INTO chunks(vault_id,id,bytes,hash,created_at) VALUES(?,?,?,?,?)').run(id,cid,bytes.length,h,now());res.status(201).json({id:cid});});
 app.get('/api/vaults/:id/chunks/:chunkId',(req,res)=>{const id=String(req.params.id),cid=uuid.parse(req.params.chunkId);access(req,id);if(!db.prepare('SELECT id FROM chunks WHERE vault_id=? AND id=?').get(id,cid))fail(404,'Attachment chunk not found.');res.type('application/octet-stream').sendFile(resolve(config.dataDir,'chunks',id,cid));});
 app.get('/api/vaults/:id/usage',(req,res)=>{const id=String(req.params.id);access(req,id);res.json({bytes:usage(id),limitBytes:quota,fileCount:(db.prepare('SELECT count(*) n FROM files WHERE vault_id=? AND deleted=0').get(id) as any).n,retentionDays:(db.prepare('SELECT retention_days n FROM vaults WHERE id=?').get(id) as any).n});});
 app.post('/api/vaults/:id/retention',(req,res)=>{const id=String(req.params.id);access(req,id,false,true);const x=z.object({days:z.number().int().min(30).max(3650)}).parse(req.body);transaction(db,()=>{db.prepare('UPDATE vaults SET retention_days=? WHERE id=?').run(x.days,id);prune(id);});res.json({ok:true});});
 app.get('/api/vaults/:id/members',(req,res)=>{const id=String(req.params.id);access(req,id);res.json({members:db.prepare('SELECT u.id,u.email,u.name,m.role FROM members m JOIN users u ON u.id=m.user_id WHERE m.vault_id=?').all(id)});});
 app.post('/api/vaults/:id/invites',(req,res)=>{const id=String(req.params.id);access(req,id,false,true);const x=z.object({role:z.enum(['viewer','editor'])}).parse(req.body),t=token();db.prepare('INSERT INTO invites(hash,vault_id,role,expires) VALUES(?,?,?,?)').run(digest(t),id,x.role,Date.now()+7*86400_000);res.json({token:t,url:`${config.origin}/?invite=${t}`});});
 app.post('/api/invites/:token/accept',(req,res)=>{const a=browser(req),h=digest(String(req.params.token));const id=transaction(db,()=>{const i=db.prepare('SELECT * FROM invites WHERE hash=? AND expires>?').get(h,Date.now()) as any;if(!i||i.used_by&&i.used_by!==a.userId)fail(404,'Invitation expired or already used.');db.prepare('INSERT OR IGNORE INTO members(vault_id,user_id,role) VALUES(?,?,?)').run(i.vault_id,a.userId,i.role);db.prepare('UPDATE invites SET used_by=? WHERE hash=?').run(a.userId,h);return i.vault_id;});res.json({vault:vault(req,id)});});
 app.delete('/api/vaults/:id/members/:userId',(req,res)=>{const id=String(req.params.id),uid=uuid.parse(req.params.userId);access(req,id,false,true);if(uid===actor(req).userId)fail(400,'The owner cannot remove themselves.');transaction(db,()=>{db.prepare('DELETE FROM members WHERE vault_id=? AND user_id=?').run(id,uid);db.prepare('DELETE FROM devices WHERE vault_id=? AND user_id=?').run(id,uid);db.prepare('DELETE FROM invites WHERE vault_id=? AND used_by=?').run(id,uid);log(actor(req).userId,'member.revoke',uid);});res.json({ok:true,keyRotationRequired:true});});
 app.post('/api/vaults/:id/rotate',(req,res)=>{const id=String(req.params.id);access(req,id,false,true);const x=z.object({expectedEpoch:z.number().int().positive(),epoch:z.number().int().positive(),salt:z.string().min(20).max(100),keyBox:box,revokeUserId:uuid.optional()}).parse(req.body);if(x.epoch!==x.expectedEpoch+1)fail(400,'Invalid key epoch.');if(x.revokeUserId===actor(req).userId)fail(400,'Cannot revoke the owner.');transaction(db,()=>{const n=db.prepare('UPDATE vaults SET salt=?,key_box=?,epoch=? WHERE id=? AND epoch=?').run(x.salt,JSON.stringify(x.keyBox),x.epoch,id,x.expectedEpoch);if(!n.changes)fail(409,'Vault keys changed. Reload first.');if(x.revokeUserId){db.prepare('DELETE FROM members WHERE vault_id=? AND user_id=?').run(id,x.revokeUserId);db.prepare('DELETE FROM devices WHERE vault_id=? AND user_id=?').run(id,x.revokeUserId);}db.prepare('DELETE FROM invites WHERE vault_id=?').run(id);log(actor(req).userId,'vault.rotate',id);});res.json({vault:vault(req,id)});});
 app.post('/api/devices',(req,res)=>{const a=browser(req),x=z.object({name:z.string().trim().min(1).max(100),vaultId:uuid}).parse(req.body);access(req,x.vaultId,true);const id=randomUUID(),t=token();db.prepare('INSERT INTO devices(id,user_id,vault_id,name,hash,created_at) VALUES(?,?,?,?,?,?)').run(id,a.userId,x.vaultId,x.name,digest(t),now());res.status(201).json({id,token:t});});
 app.get('/api/devices',(req,res)=>{const a=browser(req);res.json({devices:db.prepare('SELECT id,name,vault_id AS vaultId,created_at AS createdAt,last_used_at AS lastUsedAt FROM devices WHERE user_id=?').all(a.userId)});});
 app.delete('/api/devices/:id',(req,res)=>{const a=browser(req);db.prepare('DELETE FROM devices WHERE id=? AND user_id=?').run(uuid.parse(req.params.id),a.userId);res.json({ok:true});});

 // Public snapshots are distinct from encrypted vault storage. Never resolve private references here.
 const siteInput=z.object({slug:z.string().regex(/^[a-z0-9][a-z0-9-]{1,62}[a-z0-9]$/),title:z.string().trim().min(1).max(200)});
 function siteAccess(req:Request,id:string){uuid.parse(id);const s=db.prepare('SELECT * FROM sites WHERE id=?').get(id) as any;if(!s)fail(404,'Site not found.');access(req,s.vault_id,false,true);return s;}
 app.get('/api/vaults/:id/sites',(req,res)=>{const id=String(req.params.id);access(req,id,false,true);res.json({sites:db.prepare('SELECT * FROM sites WHERE vault_id=?').all(id).map(siteRecord)});});
 app.post('/api/vaults/:id/sites',(req,res)=>{const id=String(req.params.id);access(req,id,false,true);const x=siteInput.parse(req.body);if(db.prepare('SELECT id FROM sites WHERE slug=?').get(x.slug))fail(409,'Site address is already in use.');const sid=randomUUID();db.prepare('INSERT INTO sites(id,vault_id,slug,title,updated_at) VALUES(?,?,?,?,?)').run(sid,id,x.slug,x.title,now());res.status(201).json({site:siteRecord(db.prepare('SELECT * FROM sites WHERE id=?').get(sid))});});
 const pathSchema=z.string().refine(safePath,'Unsafe path');
 const publication=z.object({expectedRevision:z.number().int().min(0),title:z.string().trim().min(1).max(200),description:z.string().max(2000),theme:z.enum(['light','dark']),accent:z.string().regex(/^#[0-9a-fA-F]{6}$/),noindex:z.boolean(),password:z.string().min(12).max(256).optional(),removePassword:z.boolean().optional(),notes:z.array(z.object({id:uuid,path:pathSchema,content:z.string().max(1_000_000),title:z.string().max(200),slug:z.string().regex(/^[\p{L}\p{N}][\p{L}\p{N}-]{0,199}$/u),updatedAt:z.iso.datetime()})).max(5000),assets:z.array(z.object({id:uuid,path:pathSchema,mime:z.string().max(100),data:z.string().max(28_000_000).regex(/^[A-Za-z0-9+/]*={0,2}$/)})).max(500)});
 app.get('/api/sites/:id/publication',(req,res)=>{const s=siteAccess(req,String(req.params.id));res.json({notes:db.prepare('SELECT id,path,title,slug,content,updated_at AS updatedAt FROM published_notes WHERE site_id=?').all(s.id),revision:s.revision});});
 app.put('/api/sites/:id',async(req,res)=>{const sid=String(req.params.id);siteAccess(req,sid);const x=publication.parse(req.body);if(new Set(x.notes.map(n=>n.id)).size!==x.notes.length||new Set(x.notes.map(n=>n.slug)).size!==x.notes.length||new Set(x.notes.map(n=>n.path)).size!==x.notes.length||new Set(x.assets.map(n=>n.id)).size!==x.assets.length||new Set(x.assets.map(n=>n.path)).size!==x.assets.length)fail(400,'Publication contains duplicate paths or IDs.');
  capacity(Buffer.byteLength(JSON.stringify(x))*2);
  const passwordHash=x.password?await hashPassword(x.password):undefined;
  const names=new Set(x.notes.flatMap(n=>[n.path,n.path.replace(/\.md$/i,''),n.path.split('/').pop()!.replace(/\.md$/i,'')]).concat(x.assets.map(a=>a.path)));
  transaction(db,()=>{const s=siteAccess(req,sid);if(s.revision!==x.expectedRevision)fail(409,'The publication changed. Refresh its preview.');const bytes=x.notes.reduce((n,f)=>n+Buffer.byteLength(f.content),0)+x.assets.reduce((n,f)=>n+Buffer.from(f.data,'base64').length,0);if(usage(s.vault_id)-publicationSize(sid)+bytes>quota)fail(413,'Vault storage limit reached.');db.prepare('DELETE FROM published_notes WHERE site_id=?').run(sid);db.prepare('DELETE FROM published_assets WHERE site_id=?').run(sid);
   for(const n of x.notes){const content=n.content.replace(/!?\[\[([^\]]+)\]\]/g,(all,target:string)=>names.has(target.split('|')[0].split('#')[0])?all:'[unpublished note]');db.prepare('INSERT INTO published_notes(site_id,id,path,title,slug,content,updated_at) VALUES(?,?,?,?,?,?,?)').run(sid,n.id,n.path,n.title,n.slug,content,n.updatedAt);}
   for(const a of x.assets){const raw=Buffer.from(a.data,'base64');if(raw.length>20*1024**2)fail(413,'Published asset exceeds 20 MiB.');db.prepare('INSERT INTO published_assets(site_id,id,path,mime,data) VALUES(?,?,?,?,?)').run(sid,a.id,a.path,a.mime,raw);}
   const ph=passwordHash??(x.removePassword?null:s.password_hash);db.prepare('UPDATE sites SET title=?,description=?,theme=?,accent=?,noindex=?,password_hash=?,published=1,revision=revision+1,updated_at=? WHERE id=?').run(x.title,x.description,x.theme,x.accent,+x.noindex,ph,now(),sid);db.prepare('DELETE FROM public_sessions WHERE site_id=?').run(sid);db.prepare('INSERT INTO publication_history(site_id,actor_id,revision,action,note_count,created_at) VALUES(?,?,?,?,?,?)').run(sid,actor(req).userId,s.revision+1,'publish',x.notes.length,now());});res.json({site:siteRecord(db.prepare('SELECT * FROM sites WHERE id=?').get(sid))});});
 app.delete('/api/sites/:id/publication',(req,res)=>{const s=siteAccess(req,String(req.params.id));transaction(db,()=>{db.prepare('UPDATE sites SET published=0,revision=revision+1,updated_at=? WHERE id=?').run(now(),s.id);db.prepare('DELETE FROM published_notes WHERE site_id=?').run(s.id);db.prepare('DELETE FROM published_assets WHERE site_id=?').run(s.id);db.prepare('DELETE FROM public_sessions WHERE site_id=?').run(s.id);db.prepare('INSERT INTO publication_history(site_id,actor_id,revision,action,note_count,created_at) VALUES(?,?,?,?,?,?)').run(s.id,actor(req).userId,s.revision+1,'unpublish',0,now());});res.json({ok:true});});
 function publicSite(req:Request,slug:string,gate=true){const s=db.prepare('SELECT * FROM sites WHERE slug=? AND published=1').get(slug) as any;if(!s)fail(404,'This site is not published.');if(gate&&s.password_hash){const cookie=req.cookies[`flint_public_${s.id}`];if(!cookie||!db.prepare('SELECT hash FROM public_sessions WHERE hash=? AND site_id=? AND expires>?').get(digest(cookie),s.id,Date.now()))fail(401,'Enter this site’s password.','SITE_PASSWORD');}return s;}
 app.get('/api/published/:slug',(req,res)=>{const s=publicSite(req,String(req.params.slug));res.json({site:publicSiteRecord(s),notes:db.prepare('SELECT id,path,title,slug,content,updated_at AS updatedAt FROM published_notes WHERE site_id=? ORDER BY path').all(s.id),assets:db.prepare('SELECT id,path,mime FROM published_assets WHERE site_id=?').all(s.id)});});
 app.post('/api/published/:slug/unlock',rate(10,15*60_000),async(req,res)=>{const s=publicSite(req,String(req.params.slug),false),x=z.object({password:z.string().max(256)}).parse(req.body);if(s.password_hash&&!await verifyPassword(x.password,s.password_hash))fail(401,'Incorrect site password.','SITE_PASSWORD');const fresh=publicSite(req,String(req.params.slug),false);if(fresh.password_hash!==s.password_hash||fresh.revision!==s.revision)fail(401,'Site access changed. Enter its current password.','SITE_PASSWORD');const t=token();db.prepare('INSERT INTO public_sessions(hash,site_id,expires) VALUES(?,?,?)').run(digest(t),s.id,Date.now()+12*3600_000);res.cookie(`flint_public_${s.id}`,t,{httpOnly:true,secure:!!config.production,sameSite:'strict',maxAge:12*3600_000,path:'/'});res.json({ok:true});});
 app.get('/api/published/:slug/assets/:assetId',(req,res)=>{const s=publicSite(req,String(req.params.slug)),a=db.prepare('SELECT * FROM published_assets WHERE site_id=? AND id=?').get(s.id,uuid.parse(req.params.assetId)) as any;if(!a)fail(404,'Asset not found.');const inline=/^image\/(png|jpeg|gif|webp|avif)$/.test(a.mime)||a.mime==='application/pdf'||/^audio\//.test(a.mime)||/^video\//.test(a.mime);res.set('Content-Type',inline?a.mime:'application/octet-stream').set('Content-Disposition',`${inline?'inline':'attachment'}; filename*=UTF-8''${encodeURIComponent(a.path.split('/').pop()!)}`).send(Buffer.from(a.data));});
 app.get('/sitemap.xml',(_req,res)=>{const rows=db.prepare('SELECT s.slug site,n.slug note,n.updated_at FROM sites s JOIN published_notes n ON n.site_id=s.id WHERE s.published=1 AND s.password_hash IS NULL AND s.noindex=0').all() as any[];res.type('application/xml').send(`<?xml version="1.0" encoding="UTF-8"?><urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">${rows.map(r=>`<url><loc>${html(config.origin)}/p/${encodeURIComponent(r.site)}/${encodeURIComponent(r.note)}</loc><lastmod>${r.updated_at}</lastmod></url>`).join('')}</urlset>`);});
 app.get('/robots.txt',(_req,res)=>res.type('text').send(`User-agent: *\nDisallow: /api/\nDisallow: /?\nSitemap: ${config.origin}/sitemap.xml\n`));
 app.use('/api',(_req,_res)=>fail(404,'Endpoint not found.'));
 if(config.staticDir){
  app.use(express.static(config.staticDir,{index:false,maxAge:0,setHeaders:(res,path)=>{if(path.includes('/assets/'))res.setHeader('Cache-Control','public, max-age=31536000, immutable');else res.setHeader('Cache-Control','no-cache');}}));
  app.get('/{*path}',(req,res,next)=>{try{let page=readFileSync(join(config.staticDir!,'index.html'),'utf8');res.set('Cache-Control','no-store');let parts:string[];try{parts=req.path.split('/').map(p=>decodeURIComponent(p));}catch{fail(400,'Invalid URL encoding.');}if(parts[1]==='p'){
   const s=publicSite(req,parts[2],false);if(s.password_hash||s.noindex)res.set('X-Robots-Tag','noindex, nofollow');
   let title='Protected notes',description='Enter the site password to continue.';
   if(!s.password_hash){const n=parts[3]?db.prepare('SELECT title FROM published_notes WHERE site_id=? AND slug=?').get(s.id,parts[3]) as any:null;if(parts[3]&&!n)fail(404,'Published note not found.');title=n?`${n.title} · ${s.title}`:s.title;description=s.description;}
   const canonical=`${config.origin}/p/${encodeURIComponent(s.slug)}${parts[3]?'/'+encodeURIComponent(parts[3]):''}`;
   page=page.replace(/<title>.*?<\/title>/,`<title>${html(title)}</title><meta name="description" content="${html(description)}"/><link rel="canonical" href="${html(canonical)}"/>`);
  }else res.set('X-Robots-Tag','noindex, nofollow');res.type('html').send(page);}catch(e){next(e);}});
 }
 app.use((err:any,_req:Request,res:Response,_next:NextFunction)=>{if(res.headersSent)return;const status=err instanceof HttpError?err.status:err instanceof z.ZodError?400:err.type==='entity.too.large'?413:500;if(status>=500)console.error('request.failed',err.code||err.name||'Error');res.status(status).json({error:status===500?'The server could not complete this request.':err instanceof z.ZodError?'Invalid request: '+err.issues.map(i=>i.path.join('.')+': '+i.message).join('; '):err.message,code:err.code,...(err instanceof HttpError?err.details:{})});});
 return{app,db,maintenance};
}
export function fileRecord(r:any):FileRecord{return{id:r.id??r.file_id,vaultId:r.vault_id,revision:r.revision,epoch:r.epoch,box:JSON.parse(r.box),...(r.manifest_box?{manifestBox:JSON.parse(r.manifest_box)}:{}),deleted:!!r.deleted,updatedAt:r.updated_at,seq:r.seq};}
function siteRecord(s:any):Site{return{id:s.id,vaultId:s.vault_id,slug:s.slug,title:s.title,description:s.description,theme:s.theme,accent:s.accent,passwordProtected:!!s.password_hash,noindex:!!s.noindex,updatedAt:s.updated_at,revision:s.revision};}
function publicSiteRecord(s:any){const{vaultId,...publicFields}=siteRecord(s);return publicFields;}
