import React,{useEffect,useState} from 'react';
import ReactMarkdown from 'react-markdown';
import remarkGfm from 'remark-gfm';
import remarkMath from 'remark-math';
import rehypeKatex from 'rehype-katex';
import type {LocalFile} from '../../shared/types';
import {frontmatter,noteTitle,resolveLink,slugify} from '../notes';
function Asset({file,load}:{file:LocalFile;load?:(f:LocalFile)=>Promise<string>}){const [src,setSrc]=useState('');useEffect(()=>{let active=true;let url='';load?.(file).then(v=>{url=v;if(active)setSrc(v);}).catch(()=>{});return()=>{active=false;if(url.startsWith('blob:'))URL.revokeObjectURL(url);};},[file.id,load]);return src?<img src={src} alt={noteTitle(file.path)} loading="lazy"/>:<span className="asset-placeholder">Attachment: {file.path}</span>;}
export function Markdown({content,path,files,onOpen,loadAsset}:{content:string;path:string;files:LocalFile[];onOpen:(id:string,anchor?:string)=>void;loadAsset?:(f:LocalFile)=>Promise<string>}){
 const source=frontmatter(content).body.replace(/!\[\[([^\]]+)\]\]/g,(_,target:string)=>{const f=resolveLink(target,path,files);if(!f)return `*Unresolved embed: ${target}*`;if(f.attachment)return `![${noteTitle(f.path)}](#asset-${f.id})`;let body=frontmatter(f.content).body;const anchor=target.split('#')[1]?.split('|')[0];if(anchor){if(anchor.startsWith('^'))body=body.split('\n').find(l=>l.endsWith(anchor))||'';else{const lines=body.split('\n');const start=lines.findIndex(l=>l.replace(/^#+\s*/,'')===anchor);if(start>=0){let end=lines.findIndex((l,i)=>i>start&&/^#+\s/.test(l));body=lines.slice(start,end<0?undefined:end).join('\n');}}}return '\n> '+body.replace(/!\[\[/g,'[[').split('\n').join('\n> ')+'\n';}).replace(/\[\[([^\]]+)\]\]/g,(_,inside:string)=>{const [target,label]=inside.split('|');const f=resolveLink(target,path,files);const anchor=target.split('#')[1];return f?`[${label||target}](#note-${f.id}${anchor?'~'+encodeURIComponent(anchor):''})`:`[${label||target}](#unresolved)`;}).replace(/^(>\s*)\[!(\w+)\][+-]?\s*(.*)$/gm,'$1**$2 $3**');
 const header=(level:number)=>(props:any)=>React.createElement('h'+level,{id:slugify(String(props.children))},props.children);
 return <div className="markdown"><ReactMarkdown remarkPlugins={[remarkGfm,remarkMath]} rehypePlugins={[rehypeKatex]} components={{p:({children})=>{const list=React.Children.toArray(children);const last=list[list.length-1];if(typeof last==='string'){const m=last.match(/\s+\^([a-zA-Z0-9-]+)\s*$/);if(m){list[list.length-1]=last.slice(0,m.index);return <p id={m[1]}>{list}</p>;}}return <p>{children}</p>;},h1:header(1),h2:header(2),h3:header(3),h4:header(4),h5:header(5),h6:header(6),a:({href,children})=>{if(href?.startsWith('#note-')){const [id,anchor]=href.slice(6).split('~');const f=files.find(f=>f.id===id);return <a href={href} title={f?.content.slice(0,220)} onClick={e=>{e.preventDefault();onOpen(id,anchor?decodeURIComponent(anchor):undefined);}}>{children}</a>;}if(href==='#unresolved')return <span className="unresolved" title="This note does not exist, is ambiguous, or is not published">{children}</span>;if(href&&!/^(https?:|mailto:|#)/i.test(href)){const f=resolveLink(href,path,files);if(f)return <a href="#" onClick={e=>{e.preventDefault();onOpen(f.id);}}>{children}</a>;}return <a href={href} target={href?.startsWith('http')?'_blank':undefined} rel="noopener noreferrer">{children}</a>;},img:({src,alt})=>{const f=src?.startsWith('#asset-')?files.find(f=>f.id===src.slice(7)):resolveLink(src||'',path,files);if(f)return <Asset file={f} load={loadAsset}/>;return <span className="asset-placeholder">{alt||'Image'} · external image omitted</span>;},input:props=><input {...props} disabled/>}}>{source}</ReactMarkdown></div>;
}
